name: wasteless
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing to pub.dev.

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.40.0
  provider: ^6.0.0
  intl: ^0.17.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.5.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
